# Generated by Django 4.0.1 on 2022-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('waste_type', models.CharField(choices=[('LIQUID WASTE', 'liquid waste'), ('SOLID WASTE', 'solid waste'), ('ORGANIC WASTE', 'Organic Waste'), ('RECYCLABLE WASTE', 'Recyclable Rubbish'), ('HAZARDOUS WASTE', 'Hazardous Waste')], max_length=100)),
                ('number_of_bins', models.IntegerField()),
            ],
        ),
    ]
