# Generated by Django 4.0.1 on 2022-06-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='79319943', editable=False, max_length=8),
        ),
    ]
