# Generated by Django 4.0.1 on 2022-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_status_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(default='90307085', editable=False, max_length=8),
        ),
    ]
